### ISSUE TITLE
(서버) 이렇게된이상 PC에 직접 클론해서 작동시켜봐야될듯. - Request body 관련 (#2)

### ISSUE THREAD

**Issue by Merseong** [osamhack2020/WEB_ROKTION_Yeonghon-s-Matdai#14]
일단 윈도우에 해봐야지

**Comment by Merseong** [comment]
POST 되긴된다..
근데 왜 DB연결이 안되니
```Bash
[0] DB connection error MongooseServerSelectionError: Could not connect to any servers in your MongoDB Atlas cluster. One common reason is that you're trying to access the database from an IP that isn't whitelisted. Make sure your current IP address is on your Atlas cluster's IP whitelist: https://docs.atlas.mongodb.com/security-whitelist/
[0]     at NativeConnection.Connection.openUri (C:\Users\CKIRUser\Desktop\WEB_ROKTION_Yeonghon-s-Matdai-master\ROKTION-server\node_modules\mongoose\lib\connection.js:800:32)
[0]     at C:\Users\CKIRUser\Desktop\WEB_ROKTION_Yeonghon-s-Matdai-master\ROKTION-server\node_modules\mongoose\lib\index.js:341:10
[0]     at promiseOrCallback (C:\Users\CKIRUser\Desktop\WEB_ROKTION_Yeonghon-s-Matdai-master\ROKTION-server\node_modules\mongoose\lib\helpers\promiseOrCallback.js:9:12)
[0]     at Mongoose.connect (C:\Users\CKIRUser\Desktop\WEB_ROKTION_Yeonghon-s-Matdai-master\ROKTION-server\node_modules\mongoose\lib\index.js:340:10)
[0]     at C:\Users\CKIRUser\Desktop\WEB_ROKTION_Yeonghon-s-Matdai-master\ROKTION-server\src\db.ts:15:26 {
[0]   reason: TopologyDescription {
[0]     type: 'ReplicaSetNoPrimary',
[0]     setName: null,
[0]     maxSetVersion: null,
[0]     maxElectionId: null,
[0]     servers: Map {
[0]       'roktion-shard-00-01.do4pn.gcp.mongodb.net:27017' => [ServerDescription],
[0]       'roktion-shard-00-02.do4pn.gcp.mongodb.net:27017' => [ServerDescription],
[0]       'roktion-shard-00-00.do4pn.gcp.mongodb.net:27017' => [ServerDescription]
[0]     },
[0]     stale: false,
[0]     compatible: true,
[0]     compatibilityError: null,
[0]     logicalSessionTimeoutMinutes: null,
[0]     heartbeatFrequencyMS: 10000,
[0]     localThresholdMS: 15,
[0]     commonWireVersion: null
[0]   }
[0] }
```

검색해보니 프록시 문제일수 있다고 하기하느데 그냥 싸지방에서 해서 문제인건가 싶다
